### ISSUE TITLE
RPC doesn't switch

### ISSUE THREAD

**Issue by Jolly-Pirate** [therealwolf42/hive-witness-essentials#2]
RPC doesn't switch to the next when it's down/unreachable.

```
Initiating Witness Watcher
watch_witness { FetchError: network timeout at: https://anyx.io/
    at Timeout.<anonymous> (/watcher/node_modules/node-fetch/lib/index.js:1448:13)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
  message: 'network timeout at: https://anyx.io/',
  type: 'request-timeout' }
----------------------------
Initiating Witness Watcher
watch_witness { FetchError: network timeout at: https://anyx.io/
    at Timeout.<anonymous> (/watcher/node_modules/node-fetch/lib/index.js:1448:13)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
  message: 'network timeout at: https://anyx.io/',
  type: 'request-timeout' }
```

**Comment by therealwolf42** [comment]
It should be resolved with the newest version!
