### ISSUE TITLE
Unable to acquire database lock

### ISSUE THREAD

**Issue by Jolly-Pirate** [therealwolf42/hive-witness-essentials#3]
```
2020-04-06T20:58:10.866Z - Witness Watcher: Active
watch_witness { RPCError: Unable to acquire database lock
    at Client.<anonymous> (/watcher/node_modules/@hivechain/dhive/lib/client.js:181:23)
    at Generator.next (<anonymous>)
    at fulfilled (/watcher/node_modules/@hivechain/dhive/lib/client.js:39:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RPCError',
  jse_shortmsg: 'Unable to acquire database lock',
  jse_info: {},
  message: 'Unable to acquire database lock' }
```

Solution I use in my code, you can try to adapt it:
```
let keepTrying = true;
    do {
      try {
        var data = await steem.api.getAccountsAsync(accountsArray);
        keepTrying = false;
      } catch (err) {
        console.log(err.message, '| RETRYING');
        utils.wait(1000); // wait a second before retrying
      }
    } while (keepTrying);
```

**Comment by therealwolf42** [comment]
fixed
