### ISSUE TITLE
Bad gateway doesn't switch RPC

### ISSUE THREAD

**Issue by Jolly-Pirate** [therealwolf42/hive-witness-essentials#5]
RPC doesn't switch when there's a bad gateway
```
watch_witness Error: HTTP 502: Bad Gateway
    at Object.<anonymous> (/watcher/node_modules/@hivechain/dhive/lib/utils.js:130:27)
    at Generator.next (<anonymous>)
    at fulfilled (/watcher/node_modules/@hivechain/dhive/lib/utils.js:39:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by therealwolf42** [comment]
Do you know what the `code` is of that error?

Example: `const timeoutErrors = ['request-timeout', 'ENOTFOUND', 'ECONNREFUSED']`

Is it `Bad Gateway`?

**Comment by therealwolf42** [comment]
fixed
